services:
  phpmyadmin:
    container_name: pma
    image: phpmyadmin
    ports:
      - 8080:80
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: ahmad
      PMA_PASSWORD: 123
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: ahmad
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 3306:3306
